[package]
name = "wegit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
