[package]
name = "rgit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_derive = "1.0"
sha1 = "0.10"
flate2 = "1.0"